Exit code: 0
Wall time: 2.2 seconds
Output:
const layers=[
 {n:'蝖祇????,c:'DGX 繚 BasePOD 繚 SuperPOD',d:'??蝬?霅????雯頝胯摮?蝞∠??箇??asePOD ?拙?隡平?郊?游?嚗uperPOD ?Ｗ?蝺??血??之閬芋 AI/HPC??,t:['DGX','HGX','NVSwitch','Base Command']},
 {n:'?脣?????',c:'NVMe 繚 GDS 繚 cuFile',d:'雿輻 GPUDirect Storage ?輸? CPU bounce buffer嚗??脣???GPU memory ?湔 DMA嚗????捱?潭?獢頂蝯梯? PCIe ???,t:['NVMe','GDS','cuFile','O_DIRECT']},
 {n:'蝭暺?鈭?,c:'Ethernet 繚 RoCE 繚 InfiniBand',d:'靘?collective communication 撖漲?豢?蝬脰楝?nfiniBand 撘瑁矽雿辣?脰??舫?皜祆改?RoCE ? Ethernet 銝?靘?RDMA??,t:['ConnectX','RDMA','RoCE','NDR']},
 {n:'蝭暺鈭?,c:'PCIe 繚 NVLink 繚 NVSwitch',d:'GPU?IC ??CPU ?祕擃??脫??湔敶梢?唾撓頝臬???蝣箔? NUMA affinity嚗?隢?擃惜隤踵??,t:['PCIe','NVLink','NUMA','P2P']},
 {n:'蝟餌絞蝞∠?',c:'NVIDIA-SMI 繚 DCGM 繚 Nsight',d:'NVIDIA-SMI ?亦??單???CGM 蝞∠?鞈?銝剖? GPU?sight ??雿?????kernel 蝝?詻?,t:['NVML','DCGM','Nsight Systems','Nsight Compute']},
 {n:'??銵憓?,c:'Driver 繚 CUDA 繚 NVCC',d:'Driver ?? GPU 摮?嚗UDA Toolkit ????啣?嚗VCC 鞎痊?矽 host/device code ?楊霅胯????脖???,t:['CUDA Runtime','NVCC','Driver API','Streams']},
 {n:'隡平撟喳',c:'NVIDIA AI Enterprise',d:'??隡平蝝?霅?擃??賡望????冽?啗??舀嚗??航?擃像?堆????舐′擃??脯?,t:['NVAIE','NGC','Run:ai','Kubernetes']},
 {n:'?撘銵?,c:'NCCL 繚 UCX 繚 Dask-CUDA',d:'NCCL 鞎痊 GPU collective嚗CX ?豢?擃頛貉楝敺?Dask-CUDA 隞?one-process-per-GPU 蝯?鞈?撌乩???,t:['NCCL','UCX','Dask','Slurm']},
 {n:'??撘澈',c:'CuPy 繚 cuDF 繚 cuML',d:'霈???皜?????蝺游?刻??⊿?靽? GPU-native嚗??閬???NumPy ??Pandas??,t:['RAPIDS','CuPy','cuDF','cuML']}
];
const projects=[
 {id:'p1',cat:'single',title:'CUDA 鞈?擏?撖阡?摰?,desc:'?葫 CPU?PU 銴ˊ?嚗? batching?inned memory ??streams 撱箇??? pipeline??,tags:['CUDA','NVCC','Streams'],goal:'????甇亦?鞈????寥??寞活???郊銝??虜擏?GPU ??pipeline??,steps:['撱箇? CPU baseline ?垢?啁垢閮?','? H2D?ernel?2H ??','撠 pinned memory ??蝺抵?','??CUDA Streams ???唾撓??蝞?,'瘥????辣?脰? GPU duty cycle'],metrics:['GPU utilization','H2D / D2H bandwidth','Kernel gap','End-to-end latency'],pain:['?餌?霈??GPU scalar ???郊','batch ??嚗????砍之?潸?蝞?,'?芷? kernel嚗蕭?亙???pipeline']},
 {id:'p2',cat:'single',title:'GPU ??頂蝯梯那?瑕',desc:'??NVIDIA-SMI?CGM ??Nsight 撱箇? GPU ?亙熒???脣???箸???,tags:['NVIDIA-SMI','DCGM','Nsight'],goal:'撱箇?瘥 GPU 蝭暺?蝺??質???瑁??摨瑟炎?亥???箇???,steps:['?日? driver?PU ??CUDA ?詨捆??,'蝜芾ˊ GPU?IC?UMA ?','?瑁? DCGM diagnostics','??Nsight Systems ????蝺?,'靽??箇?銝西身摰撣賊?瑼?],metrics:['Temperature / Power','PCIe link width','ECC / XID errors','SM occupancy'],pain:['nvidia-smi ??CUDA 憿舐內鋡怨炊隤 Toolkit ?','GPU ??NIC 頝?NUMA socket','?芰? utilization嚗??敺???]},
 {id:'p3',cat:'cluster',title:'BasePOD嚗uperPOD 閮剛?撌乩???,desc:'隞亙極雿?頛PU ?賊??摮????瘙?摰?隡平 AI ?ａ??詨???,tags:['DGX','BasePOD','SuperPOD'],goal:'?平??瘙???閮??雯頝胯摮恣??璈摰寥?閮剛???,steps:['摰儔閮毀?隢?憭??園?瘙?,'隡啁? GPU memory ??暺?璅?,'?蔭 compute?torage?anagement fabric','瘥? BasePOD?uperPOD ??Certified Systems','摰?摰寥????梯??游?閮'],metrics:['Scaling efficiency','Storage throughput / GPU','Network oversubscription','Cluster availability'],pain:['?芰 GPU ?賊?隡啁?蝟餌絞','敹賜 checkpoint ??dataset I/O','??NVAIE ?嗆?蝖祇??嗆?']},
 {id:'p4',cat:'cluster',title:'RDMA ??NCCL 蝬脰楝撖阡?摰?,desc:'瘥? TCP Ethernet?oCE ??InfiniBand嚗?霅?GPUDirect RDMA ?臬?迤????,tags:['InfiniBand','RoCE','NCCL'],goal:'??multi-node collective 撱箇??舫??曄?撱園?撖祈? scaling ?箸???,steps:['蝣箄?撖阡?慦??ink layer ??link rate','?瑁?雿? RDMA bandwidth 皜祈岫','撽? GPU?IC PCIe affinity','?瑁? NCCL tests 撱箇? collective baseline','瘥? TCP?oCE嚗B ?矽?∪?蝯?'],metrics:['AllReduce bandwidth','Latency','Packet retry / drop','Scaling efficiency'],pain:['??RJ45??蝥? IB ?嗅?銝??','NIC ?舀 RDMA嚗??隞粥 Socket','RoCE lossless ??congestion 閮剖?銝???]},
 {id:'p5',cat:'app',title:'RAPIDS GPU-native 鞈?蝞∠?',desc:'隞?cuDF?uPy?uML 銝脰絲 ETL?敺萄極蝔?璅∪?閮毀嚗????CPU??,tags:['cuDF','CuPy','cuML'],goal:'撠?Pandas嚗umPy嚗cikit-learn 撌乩?瘚??寥?蝡臬蝡?GPU-native pipeline??,steps:['?葫 CPU pipeline baseline','??cuDF ?誨 DataFrame ??','??CuPy ??DLPack 鈭斗????','隞?cuML ?瑁?閮毀??隡?,'瑼Ｘ????host transfer ??甇?],metrics:['End-to-end speedup','GPU memory peak','Host transfers','Model parity'],pain:['?芣?芋??ETL 隞 CPU','鞈???撘???銴ˊ','瞍?瘜????sklearn 銝阡?摰蝑']},
 {id:'p6',cat:'app cluster',title:'Dask 憭?GPU ?游??',desc:'敺 GPU 撱嗡撓?喳璈? GPU ??蝭暺??曉 partition?huffle ?雯頝舐?詻?,tags:['Dask-CUDA','UCX','RMM'],goal:'?其??抒蝛拙??抒???銝?撱箇? one-process-per-GPU ???????,steps:['蝣箄???GPU 撌脤?????','撱箇? LocalCUDACluster baseline','隤踵瘥?worker 2?? ??partitions 韏瑟葫','閮剖? RMM pool ??spill 蝑','?游?憭?暺蒂?葫??雿?'],metrics:['Worker balance','Task overhead','Spill volume','Strong / weak scaling'],pain:['鞈?憭芸?隞撥銵????','partition ??????鞎?','shuffle ?雯頝臬???蝞??]}
];
const diagnoses=[
 {q:'GPU 雿輻?蕭擃蕭雿?,title:'?鞈?靘???甇亦征瘣?,body:'?虜銝 GPU 蝞?銝雲嚗 GPU ?函?敺?CPU?????交??郊?????湔???嚗?閬???函???,checks:['Nsight嚗ernel 銋??征??,'CPU嚗ataLoader / ETL 憌賢?摨?,'CUDA嚗?甇?API ????memcpy','Pipeline嚗?擃?batch?refetch?ouble buffer']},
 {q:'憭?GPU 瘥 GPU ??,title:'閮???頞喃誑?文像??',body:'瘥?瘥憚??????NCCL collective ????????璅∪?憭芸?嚗???蝔??郊??航擃撟唾??嗥???,checks:['NCCL tests 撱箇?蝬脰楝?箇?','蝣箄? NVLink / P2P 頝臬?','?葫 collective ????','敺璈? GPU ??喳?蝭暺?]},
 {q:'GPU 閮擃?閬?OOM',title:'瑼Ｘ撜啣潦??? partition',body:'撟喳?雿輻??擃??航??葉????蝣??仃?遣蝡?memory timeline 銝行?嗆???worker ???????,checks:['RMM pool ??allocator','銝剝? tensor ??望?','Dask partition 憭批?','Spill ?臬????芸援']},
 {q:'IB 撌脣?鋆??漲??TCP',title:'撽???臬??韏?RDMA',body:'蝖祇?摮銝??潸??楝敺??? link?DMA?PU peer memory?CX ??NCCL ?惜撽???,checks:['Port state / link rate','RDMA bandwidth baseline','GPU?IC NUMA affinity','NCCL / UCX debug transport']},
 {q:'?脣?敺翰雿?GPU ???啗???,title:'?園?航??CPU bounce buffer',body:'蝣箄?撖阡? I/O 頝臬??equest size ??獢頂蝯晞璇辣?拙?嚗閰摯 GPUDirect Storage ??cuFile??,checks:['Storage standalone throughput','CPU memory copy bandwidth','GDS compatibility mode','I/O alignment ??batch size']}
];
const map=document.querySelector('#stack-map'),detail=document.querySelector('#layer-detail');
function selectLayer(i){document.querySelectorAll('.layer').forEach((e,j)=>e.classList.toggle('active',i===j));let x=layers[i];detail.innerHTML=`<p class="eyebrow">LAYER ${String(i+1).padStart(2,'0')}</p><h3>${x.n}</h3><p>${x.d}</p><div class="tag-list">${x.t.map(v=>`<span class="tag">${v}</span>`).join('')}</div>`}
layers.forEach((x,i)=>{let b=document.createElement('button');b.className='layer';b.innerHTML=`<span>${x.n}</span><code>${x.c}</code>`;b.onclick=()=>selectLayer(i);map.appendChild(b)});selectLayer(8);
const grid=document.querySelector('#project-grid');let activeFilter='all';
function renderProjects(){let query=document.querySelector('#project-search').value.toLowerCase();grid.innerHTML='';projects.filter(p=>(activeFilter==='all'||p.cat.includes(activeFilter))&&(`${p.title} ${p.desc} ${p.tags.join(' ')}`.toLowerCase().includes(query))).forEach((p,i)=>{let el=document.createElement('article');el.className='project-card';el.innerHTML=`<span class="card-index">PROJECT / ${String(i+1).padStart(2,'0')}</span><h3>${p.title}</h3><p>${p.desc}</p><div class="card-tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="card-footer"><button class="open-project" data-id="${p.id}">?亦?撠? ??/button><label title="璅?摰?"><input class="complete" type="checkbox" data-id="${p.id}" ${localStorage.getItem(p.id)==='1'?'checked':''}></label></div>`;grid.appendChild(el)});updateProgress()}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderProjects()});document.querySelector('#project-search').oninput=renderProjects;
grid.onclick=e=>{if(e.target.matches('.open-project'))openProject(e.target.dataset.id);if(e.target.matches('.complete')){localStorage.setItem(e.target.dataset.id,e.target.checked?'1':'0');updateProgress()}};
function updateProgress(){let n=projects.filter(p=>localStorage.getItem(p.id)==='1').length;document.querySelector('#progress-label').textContent=`${n} / 6 摰?`;document.querySelector('#progress-bar').style.width=`${n/6*100}%`}
const dialog=document.querySelector('#project-dialog');function openProject(id){let p=projects.find(x=>x.id===id);document.querySelector('#dialog-content').innerHTML=`<p class="eyebrow">PROJECT BLUEPRINT</p><h2 class="dialog-title">${p.title}</h2><p>${p.goal}</p><div class="dialog-grid"><div><h4>撖虫??挾</h4><ol>${p.steps.map(x=>`<li>${x}</li>`).join('')}</ol></div><div><h4>撽??</h4><ul>${p.metrics.map(x=>`<li>${x}</li>`).join('')}</ul><h4>撣貉???</h4><ul>${p.pain.map(x=>`<li>${x}</li>`).join('')}</ul></div></div>`;dialog.showModal()};document.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
const symptomBox=document.querySelector('#symptoms'),diagnosis=document.querySelector('#diagnosis');function selectDiagnosis(i){document.querySelectorAll('.symptom').forEach((e,j)=>e.classList.toggle('active',i===j));let x=diagnoses[i];diagnosis.innerHTML=`<p class="eyebrow">DIAGNOSIS / ${String(i+1).padStart(2,'0')}</p><h3>${x.title}</h3><p>${x.body}</p><div class="checks">${x.checks.map((c,j)=>`<div class="check"><b>0${j+1}</b> ${c}</div>`).join('')}</div>`}diagnoses.forEach((x,i)=>{let b=document.createElement('button');b.className='symptom';b.textContent=x.q;b.onclick=()=>selectDiagnosis(i);symptomBox.appendChild(b)});selectDiagnosis(0);
document.querySelector('#theme-toggle').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('theme')==='light')document.body.classList.add('light');renderProjects();

