const layers=[
 {n:'硬體與叢集',c:'DGX · BasePOD · SuperPOD',d:'提供經驗證的運算、網路、儲存與管理基礎。BasePOD 適合企業逐步擴展；SuperPOD 面向緊密耦合的大規模 AI/HPC。',t:['DGX','HGX','NVSwitch','Base Command']},
 {n:'儲存與資料通道',c:'NVMe · GDS · cuFile',d:'使用 GPUDirect Storage 避開 CPU bounce buffer，讓儲存與 GPU memory 直接 DMA；成效仍取決於檔案系統與 PCIe 拓撲。',t:['NVMe','GDS','cuFile','O_DIRECT']},
 {n:'節點間互連',c:'Ethernet · RoCE · InfiniBand',d:'依 collective communication 密度選擇網路。InfiniBand 強調低延遲與可預測性；RoCE 則在 Ethernet 上提供 RDMA。',t:['ConnectX','RDMA','RoCE','NDR']},
 {n:'節點內互連',c:'PCIe · NVLink · NVSwitch',d:'GPU、NIC 與 CPU 的實體拓撲會直接影響傳輸路徑。先確保 NUMA affinity，再談軟體層調校。',t:['PCIe','NVLink','NUMA','P2P']},
 {n:'系統管理',c:'NVIDIA-SMI · DCGM · Nsight',d:'NVIDIA-SMI 查看即時狀態、DCGM 管理資料中心 GPU、Nsight 則定位時間線與 kernel 級瓶頸。',t:['NVML','DCGM','Nsight Systems','Nsight Compute']},
 {n:'開發與執行環境',c:'Driver · CUDA · NVCC',d:'Driver 提供 GPU 存取，CUDA Toolkit 提供開發環境，NVCC 負責協調 host/device code 的編譯。三者角色不同。',t:['CUDA Runtime','NVCC','Driver API','Streams']},
 {n:'企業平台',c:'NVIDIA AI Enterprise',d:'提供企業級驗證軟體、生命週期、安全更新與支援；它是軟體平台，而不是硬體拓撲。',t:['NVAIE','NGC','Run:ai','Kubernetes']},
 {n:'分散式執行',c:'NCCL · UCX · Dask-CUDA',d:'NCCL 負責 GPU collective，UCX 選擇高速傳輸路徑，Dask-CUDA 以 one-process-per-GPU 組織資料工作。',t:['NCCL','UCX','Dask','Slurm']},
 {n:'應用與函式庫',c:'CuPy · cuDF · cuML',d:'讓資料從清理、轉換、訓練到推論盡量保持 GPU-native，避免反覆轉成 NumPy 或 Pandas。',t:['RAPIDS','CuPy','cuDF','cuML']}
];
const projects=[
 {id:'p1',url:'https://jjfishjj.github.io/cuda-data-residency-lab/',cat:'single',title:'CUDA 資料駐留實驗室',desc:'量測 CPU↔GPU 複製成本，透過 batching、pinned memory 與 streams 建立重疊 pipeline。',tags:['CUDA','NVCC','Streams'],goal:'把小型、同步的資料處理改造成批次、非同步且資料常駐 GPU 的 pipeline。',steps:['建立 CPU baseline 與端到端計時','分離 H2D、kernel、D2H 時間','導入 pinned memory 與雙緩衝','用 CUDA Streams 重疊傳輸與運算','比較吞吐量、延遲與 GPU duty cycle'],metrics:['GPU utilization','H2D / D2H bandwidth','Kernel gap','End-to-end latency'],pain:['頻繁讀取 GPU scalar 造成同步','batch 過小，啟動成本大於計算','只量 kernel，忽略完整 pipeline']},
 {id:'p2',url:'https://jjfishjj.github.io/gpu-system-diagnostics-lab/',cat:'single',title:'GPU 拓撲與系統診斷台',desc:'用 NVIDIA-SMI、DCGM 與 Nsight 建立 GPU 健康、拓撲和效能基準。',tags:['NVIDIA-SMI','DCGM','Nsight'],goal:'建立每台 GPU 節點上線前都能重複執行的健康檢查與效能基線。',steps:['盤點 driver、GPU 與 CUDA 相容性','繪製 GPU、NIC、NUMA 拓撲','執行 DCGM diagnostics','用 Nsight Systems 捕捉時間線','保存基線並設定異常門檻'],metrics:['Temperature / Power','PCIe link width','ECC / XID errors','SM occupancy'],pain:['nvidia-smi 的 CUDA 顯示被誤認為 Toolkit 版本','GPU 與 NIC 跨 NUMA socket','只看 utilization，未看等待原因']},
 {id:'p3',url:'https://jjfishjj.github.io/pod-architecture-planner/',cat:'cluster',title:'BasePOD／SuperPOD 設計工作坊',desc:'以工作負載、GPU 數量、儲存與營運需求，完成企業 AI 叢集選型。',tags:['DGX','BasePOD','SuperPOD'],goal:'把業務需求轉換成計算、網路、儲存、管理與機房容量設計。',steps:['定義訓練、推論與多租戶需求','估算 GPU memory 與節點規模','配置 compute、storage、management fabric','比較 BasePOD、SuperPOD 與 Certified Systems','完成容量、電力、散熱與擴展計畫'],metrics:['Scaling efficiency','Storage throughput / GPU','Network oversubscription','Cluster availability'],pain:['只用 GPU 數量估算系統','忽略 checkpoint 與 dataset I/O','把 NVAIE 當成硬體架構']},
 {id:'p4',url:'https://jjfishjj.github.io/rdma-nccl-network-lab/',cat:'cluster',title:'RDMA 與 NCCL 網路實驗室',desc:'比較 TCP Ethernet、RoCE 與 InfiniBand，驗證 GPUDirect RDMA 是否真正生效。',tags:['InfiniBand','RoCE','NCCL'],goal:'為 multi-node collective 建立可重現的延遲、頻寬與 scaling 基準。',steps:['確認實體媒介、link layer 與 link rate','執行低階 RDMA bandwidth 測試','驗證 GPU、NIC PCIe affinity','執行 NCCL tests 建立 collective baseline','比較 TCP、RoCE／IB 與調校後結果'],metrics:['AllReduce bandwidth','Latency','Packet retry / drop','Scaling efficiency'],pain:['把 RJ45、光纖與 IB 當同一分類','NIC 支援 RDMA，但應用仍走 Socket','RoCE lossless 與 congestion 設定不完整']},
 {id:'p5',url:'https://jjfishjj.github.io/rapids-gpu-pipeline/',cat:'app',title:'RAPIDS GPU-native 資料管線',desc:'以 cuDF、CuPy、cuML 串起 ETL、特徵工程與模型訓練，避免回到 CPU。',tags:['cuDF','CuPy','cuML'],goal:'將 Pandas／NumPy／scikit-learn 工作流程改造成端到端 GPU-native pipeline。',steps:['量測 CPU pipeline baseline','用 cuDF 取代 DataFrame 處理','用 CuPy 或 DLPack 交換陣列','以 cuML 執行訓練與評估','檢查所有隱性 host transfer 與同步'],metrics:['End-to-end speedup','GPU memory peak','Host transfers','Model parity'],pain:['只替換模型，ETL 仍在 CPU','資料型別或格式轉換造成複製','演算法或參數與 sklearn 並非完全等價']},
 {id:'p6',url:'https://jjfishjj.github.io/dask-multigpu-scaling-lab/',cat:'app cluster',title:'Dask 多 GPU 擴展挑戰',desc:'從單 GPU 延伸至單機多 GPU 和多節點，找出 partition、shuffle 與網路瓶頸。',tags:['Dask-CUDA','UCX','RMM'],goal:'在不犧牲穩定性的前提下，建立 one-process-per-GPU 的資料分析叢集。',steps:['確認單 GPU 已達合理效率','建立 LocalCUDACluster baseline','調整每 worker 2–4 個 partitions 起測','設定 RMM pool 與 spill 策略','擴展多節點並量測通訊佔比'],metrics:['Worker balance','Task overhead','Spill volume','Strong / weak scaling'],pain:['資料太小仍強行分散式','partition 過多造成排程負擔','shuffle 與網路吞掉計算收益']}
];
const diagnoses=[
 {q:'GPU 使用率忽高忽低',title:'先查資料供應與同步空洞',body:'這通常不是 GPU 算力不足，而是 GPU 在等待 CPU、資料載入或同步。先看完整時間線，不要只看瞬時利用率。',checks:['Nsight：kernel 之間的空白','CPU：DataLoader / ETL 飽和度','CUDA：同步 API 與小型 memcpy','Pipeline：提高 batch、prefetch、double buffer']},
 {q:'多 GPU 比單 GPU 慢',title:'計算量不足以攤平通訊',body:'比較每輪運算時間與 NCCL collective 時間。如果資料或模型太小，啟動、排程和同步開銷可能高於平行收益。',checks:['NCCL tests 建立網路基線','確認 NVLink / P2P 路徑','量測 collective 時間占比','從單機多 GPU 再擴至多節點']},
 {q:'GPU 記憶體反覆 OOM',title:'檢查峰值、碎片與 partition',body:'平均使用量不高仍可能因瞬間中間結果或碎片化而失敗。建立 memory timeline 並控制每個 worker 的資料分區。',checks:['RMM pool 與 allocator','中間 tensor 生命週期','Dask partition 大小','Spill 是否造成效能雪崩']},
 {q:'IB 已安裝但速度像 TCP',title:'驗證應用是否真的走 RDMA',body:'硬體存在不等於資料路徑生效。從 link、RDMA、GPU peer memory、UCX 到 NCCL 逐層驗證。',checks:['Port state / link rate','RDMA bandwidth baseline','GPU–NIC NUMA affinity','NCCL / UCX debug transport']},
 {q:'儲存很快但 GPU 吃不到資料',title:'瓶頸可能在 CPU bounce buffer',body:'確認實際 I/O 路徑、request size 與檔案系統。若條件適合，可評估 GPUDirect Storage 與 cuFile。',checks:['Storage standalone throughput','CPU memory copy bandwidth','GDS compatibility mode','I/O alignment 與 batch size']}
];
const map=document.querySelector('#stack-map'),detail=document.querySelector('#layer-detail');
function selectLayer(i){document.querySelectorAll('.layer').forEach((e,j)=>e.classList.toggle('active',i===j));let x=layers[i];detail.innerHTML=`<p class="eyebrow">LAYER ${String(i+1).padStart(2,'0')}</p><h3>${x.n}</h3><p>${x.d}</p><div class="tag-list">${x.t.map(v=>`<span class="tag">${v}</span>`).join('')}</div>`}
layers.forEach((x,i)=>{let b=document.createElement('button');b.className='layer';b.innerHTML=`<span>${x.n}</span><code>${x.c}</code>`;b.onclick=()=>selectLayer(i);map.appendChild(b)});selectLayer(8);
const grid=document.querySelector('#project-grid');let activeFilter='all';
function renderProjects(){let query=document.querySelector('#project-search').value.toLowerCase();grid.innerHTML='';projects.filter(p=>(activeFilter==='all'||p.cat.includes(activeFilter))&&(`${p.title} ${p.desc} ${p.tags.join(' ')}`.toLowerCase().includes(query))).forEach((p,i)=>{let el=document.createElement('article');el.className='project-card';el.innerHTML=`<span class="card-index">PROJECT / ${String(i+1).padStart(2,'0')}</span><h3>${p.title}</h3><p>${p.desc}</p><div class="card-tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="card-footer"><div class="card-actions"><a class="launch-project" href="${p.url}">啟動實驗 ↗</a><button class="open-project" data-id="${p.id}">查看藍圖</button></div><label title="標記完成"><input class="complete" type="checkbox" data-id="${p.id}" ${localStorage.getItem(p.id)==='1'?'checked':''}></label></div>`;grid.appendChild(el)});updateProgress()}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderProjects()});document.querySelector('#project-search').oninput=renderProjects;
grid.onclick=e=>{if(e.target.matches('.open-project'))openProject(e.target.dataset.id);if(e.target.matches('.complete')){localStorage.setItem(e.target.dataset.id,e.target.checked?'1':'0');updateProgress()}};
function updateProgress(){let n=projects.filter(p=>localStorage.getItem(p.id)==='1').length;document.querySelector('#progress-label').textContent=`${n} / 6 完成`;document.querySelector('#progress-bar').style.width=`${n/6*100}%`}
const dialog=document.querySelector('#project-dialog');function openProject(id){let p=projects.find(x=>x.id===id);document.querySelector('#dialog-content').innerHTML=`<p class="eyebrow">PROJECT BLUEPRINT</p><h2 class="dialog-title">${p.title}</h2><p>${p.goal}</p><div class="dialog-grid"><div><h4>實作階段</h4><ol>${p.steps.map(x=>`<li>${x}</li>`).join('')}</ol></div><div><h4>驗收指標</h4><ul>${p.metrics.map(x=>`<li>${x}</li>`).join('')}</ul><h4>常見痛點</h4><ul>${p.pain.map(x=>`<li>${x}</li>`).join('')}</ul></div></div>`;dialog.showModal()};document.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
const symptomBox=document.querySelector('#symptoms'),diagnosis=document.querySelector('#diagnosis');function selectDiagnosis(i){document.querySelectorAll('.symptom').forEach((e,j)=>e.classList.toggle('active',i===j));let x=diagnoses[i];diagnosis.innerHTML=`<p class="eyebrow">DIAGNOSIS / ${String(i+1).padStart(2,'0')}</p><h3>${x.title}</h3><p>${x.body}</p><div class="checks">${x.checks.map((c,j)=>`<div class="check"><b>0${j+1}</b> ${c}</div>`).join('')}</div>`}diagnoses.forEach((x,i)=>{let b=document.createElement('button');b.className='symptom';b.textContent=x.q;b.onclick=()=>selectDiagnosis(i);symptomBox.appendChild(b)});selectDiagnosis(0);
document.querySelector('#theme-toggle').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('theme')==='light')document.body.classList.add('light');renderProjects();
